# Site
name: "Melabit"
description: "Mac e programmazione, con un tocco di retrocomputing"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
# disqus: "sabinomaggi"
email: "sabino.maggi@@gmail.com"
# mailchimp-list: ""

include: ["_pages"]
permalink: /:year/:month/:day/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-regex-replace

authors:
    "Sabino Maggi":
      name:           Sabino Maggi
      site:           https://melabit.wordpress.com
      avatar:         assets/images/SM_400x400.png
      bio:            "Uso da molti anni prevalentemente il Mac, davanti al quale passo la maggior parte della giornata. E mi piace anche Unix — che è il motore che gira sotto l’interfaccia amichevole e graficamente strepitosa di OS X — e la sua incarnazione moderna, Linux.
In questo blog condivido alcuni spunti e idee che derivano da quello che faccio ogni giorno e che hanno poco spazio altrove.
Argomenti a volte ostici ma che, se vengono affrontati con il tono giusto, possono diventare estremamente interessanti e rendere molto più produttivo e flessibile l’uso quotidiano del computer."
      email:          sabino.maggi@gmail.com
      twitter:        https://twitter.com/sabinomaggi

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Sabino Maggi
      avatar: /assets/images/SM_400x400.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
