# Site
name: "Melabit"
description: "Mac e programmazione, con un tocco di retrocomputing"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
# disqus: "sabinomaggi"
email: "sabino.maggi@@gmail.com"
mailchimp-list: ""

include: ["_pages"]
permalink: /:year/:month/:day/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-regex-replace

authors:
    "Sabino Maggi":
      name:           Sabino Maggi
      site:           https://melabit.wordpress.com
      avatar:         assets/images/SM_400x400.png
      bio:            ""
      email:          sabino.maggi@gmail.com
      twitter:        https://twitter.com/sabinomaggi

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Sabino Maggi
      avatar: /assets/images/SM_400x400.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
