#--- Site ---
name: "Melabit"
description: "Mac e programmazione, con un tocco di retrocomputing"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
siteurl: "http://192.168.1.102"
## siteurl: "http://152.70.43.19"
## siteurl: "http://94.237.81.102"
# disqus: "sabinomaggi"
email: "sabino.maggi@gmail.com"
# mailchimp-list: ""

include: ["_pages"]
permalink: /:year/:month/:day/:title/

#--- Plugins ---
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-regex-replace
  # - jekyll-polyglot

authors:
    Sabino Maggi:
      name:           Sabino Maggi
      site:           https://melabit.wordpress.com
      avatar:         assets/images/SM_400x400.png
      email:          sabino.maggi@gmail.com
      twitter:        https://twitter.com/sabinomaggi

#--- Defaults ---
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Sabino Maggi
      avatar: /assets/images/SM_400x400.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

#--- Syntax ---
markdown: kramdown
highlighter: rouge

# #---  Paginate ---
# paginate: 10

#--- Paginate-v2 ---
pagination:
  enabled: true
  # locale: en
  offset: 4
  per_page: 8
  # permalink: "/page:num/"
  sort_reverse: true
  debug: true

# #--- Polyglot ---
# languages: [en, it]
# default_lang: en
# exclude_from_localization: ["assets/css", "assets/img"]
# parallel_localization: false
#
# sass:
#   sourcemap: never

#--- Custom variables ---
# Polyglot does not work well with Paginate-v2
# define these two variables instead
locales: [en, it]
default_locale: en

#--- Comma comments ---
commentserver: http://localhost:5888
## commentserver: http://152.70.43.19:5888
## commentserver: http://94.237.81.102:5888

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
